# Generated by Django 5.2.1 on 2025-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
