# Generated by Django 5.2.1 on 2025-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0005_alter_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
