# Generated by Django 5.2.1 on 2025-07-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0006_alter_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
