# Generated by Django 5.2.1 on 2025-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0007_alter_product_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
